#Requires -Version 5.1
<#
.SYNOPSIS
    win-sweep change verification — confirm optimization changes have taken effect.
.DESCRIPTION
    Re-scans services, startup items, and scheduled tasks to verify expected changes.
    Can compare against a backup CSV file to detect differences.
    Also supports verifying that deleted items (services, tasks, paths, registry keys)
    are truly gone, and checking for pending-reboot state.
.PARAMETER BackupCsv
    Path to the backup CSV file generated by optimize-services.ps1 (optional).
    When provided, compares before/after differences.
.PARAMETER CheckServices
    Service list to verify (JSON format), same format as optimize-services.ps1.
    Example: '[{"Name":"DiagTrack","Target":"Disabled"}]'
.PARAMETER CheckTasks
    Array of scheduled task names to verify, expected to all be Disabled.
.PARAMETER CheckStartups
    Array of startup item names to verify have been removed from Run.
.PARAMETER CheckAbsent
    JSON array of items expected to be absent after cleanup.
    Each object has Type (Service|Task|Registry|Path) and Name/Path.
    Example: '[{"Type":"Service","Name":"SvcName"},{"Type":"Path","Path":"C:\\old\\dir"}]'
.PARAMETER CheckPendingReboot
    Check for pending reboot state (PendingFileRenameOperations, delete-pending services).
#>

[CmdletBinding()]
param(
    [string]$BackupCsv,
    [string]$CheckServices,
    [string[]]$CheckTasks,
    [string[]]$CheckStartups,
    [string]$CheckAbsent,
    [switch]$CheckPendingReboot
)

$hasWork = $false
$passCount = 0
$failCount = 0

# ── Service verification ──
if ($CheckServices) {
    $hasWork = $true
    $svcList = $CheckServices | ConvertFrom-Json
    Write-Host "`n=== Service Status Verification ===" -ForegroundColor Cyan

    foreach ($item in $svcList) {
        $current = Get-CimInstance Win32_Service -Filter "Name='$($item.Name)'" -ErrorAction SilentlyContinue
        if (-not $current) {
            Write-Host "  [?] $($item.Name) — service not found" -ForegroundColor DarkYellow
            continue
        }

        $expected = switch ($item.Target) {
            'Manual'   { 'Manual' }
            'Disabled' { 'Disabled' }
            'Auto'     { 'Auto' }
        }

        if ($current.StartMode -eq $expected) {
            Write-Host "  [PASS] $($item.Name) = $($current.StartMode)" -ForegroundColor Green
            $passCount++
        } else {
            Write-Host "  [FAIL] $($item.Name) — expected $expected, actual $($current.StartMode)" -ForegroundColor Red
            $failCount++
        }
    }
}

# ── Scheduled task verification ──
if ($CheckTasks -and $CheckTasks.Count -gt 0) {
    $hasWork = $true
    Write-Host "`n=== Scheduled Task Status Verification ===" -ForegroundColor Cyan

    foreach ($taskName in $CheckTasks) {
        $task = Get-ScheduledTask -TaskName $taskName -ErrorAction SilentlyContinue
        if (-not $task) {
            Write-Host "  [?] $taskName — task not found" -ForegroundColor DarkYellow
            continue
        }

        if ($task.State -eq 'Disabled') {
            Write-Host "  [PASS] $taskName = Disabled" -ForegroundColor Green
            $passCount++
        } else {
            Write-Host "  [FAIL] $taskName — expected Disabled, actual $($task.State)" -ForegroundColor Red
            $failCount++
        }
    }
}

# ── Startup item verification ──
if ($CheckStartups -and $CheckStartups.Count -gt 0) {
    $hasWork = $true
    Write-Host "`n=== Startup Item Verification ===" -ForegroundColor Cyan

    $runPath = 'HKCU:\Software\Microsoft\Windows\CurrentVersion\Run'
    $disPath = 'HKCU:\Software\Microsoft\Windows\CurrentVersion\RunDisabled'

    foreach ($name in $CheckStartups) {
        $inRun = $false
        $inDisabled = $false
        try { $null = (Get-ItemProperty $runPath -Name $name -ErrorAction Stop); $inRun = $true } catch {}
        try { $null = (Get-ItemProperty $disPath -Name $name -ErrorAction Stop); $inDisabled = $true } catch {}

        if (-not $inRun -and $inDisabled) {
            Write-Host "  [PASS] '$name' — moved from Run to RunDisabled" -ForegroundColor Green
            $passCount++
        } elseif ($inRun) {
            Write-Host "  [FAIL] '$name' — still in Run (not disabled)" -ForegroundColor Red
            $failCount++
        } else {
            Write-Host "  [?] '$name' — not found in either Run or RunDisabled" -ForegroundColor DarkYellow
        }
    }
}

# ── Backup comparison ──
if ($BackupCsv) {
    $hasWork = $true
    Write-Host "`n=== Service Configuration Comparison (vs backup) ===" -ForegroundColor Cyan

    if (-not (Test-Path $BackupCsv)) {
        Write-Error "Backup file not found: $BackupCsv"
    } else {
        $before = Import-Csv $BackupCsv
        $changed = @()

        foreach ($old in $before) {
            $current = Get-CimInstance Win32_Service -Filter "Name='$($old.Name)'" -ErrorAction SilentlyContinue
            if ($current -and $current.StartMode -ne $old.StartMode) {
                $changed += [PSCustomObject]@{
                    Name    = $old.Name
                    Before  = $old.StartMode
                    After   = $current.StartMode
                    State   = $current.State
                }
            }
        }

        if ($changed.Count -gt 0) {
            Write-Host "  $($changed.Count) services have changed startup mode:" -ForegroundColor Yellow
            $changed | Format-Table -AutoSize
        } else {
            Write-Host "  No changes (all service startup modes match backup)." -ForegroundColor DarkGray
        }
    }
}

# ── Absent item verification (deletion checks) ──
if ($CheckAbsent) {
    $hasWork = $true
    $absentList = $CheckAbsent | ConvertFrom-Json
    Write-Host "`n=== Absent Item Verification (expected to be gone) ===" -ForegroundColor Cyan

    foreach ($item in $absentList) {
        switch ($item.Type) {
            'Service' {
                $svc = Get-CimInstance Win32_Service -Filter "Name='$($item.Name)'" -ErrorAction SilentlyContinue
                $regExists = Test-Path "HKLM:\SYSTEM\CurrentControlSet\Services\$($item.Name)"
                if (-not $svc -and -not $regExists) {
                    Write-Host "  [PASS] Service '$($item.Name)' — fully removed" -ForegroundColor Green
                    $passCount++
                } elseif ($svc) {
                    Write-Host "  [FAIL] Service '$($item.Name)' — still exists (State: $($svc.State))" -ForegroundColor Red
                    $failCount++
                } else {
                    Write-Host "  [WARN] Service '$($item.Name)' — registry key exists (may be delete-pending, reboot to finalize)" -ForegroundColor Yellow
                    $failCount++
                }
            }
            'Task' {
                $task = Get-ScheduledTask -TaskName $item.Name -ErrorAction SilentlyContinue
                if (-not $task) {
                    Write-Host "  [PASS] Task '$($item.Name)' — fully removed" -ForegroundColor Green
                    $passCount++
                } else {
                    Write-Host "  [FAIL] Task '$($item.Name)' — still exists (State: $($task.State))" -ForegroundColor Red
                    $failCount++
                }
            }
            'Registry' {
                $path = $item.Path
                if (-not (Test-Path $path)) {
                    Write-Host "  [PASS] Registry '$path' — removed" -ForegroundColor Green
                    $passCount++
                } else {
                    Write-Host "  [FAIL] Registry '$path' — still exists" -ForegroundColor Red
                    $failCount++
                }
            }
            'Path' {
                $path = $item.Path
                if (-not (Test-Path $path)) {
                    Write-Host "  [PASS] Path '$path' — removed" -ForegroundColor Green
                    $passCount++
                } else {
                    Write-Host "  [FAIL] Path '$path' — still exists" -ForegroundColor Red
                    $failCount++
                }
            }
            default {
                Write-Host "  [?] Unknown type '$($item.Type)'" -ForegroundColor DarkYellow
            }
        }
    }
}

# ── Pending reboot check ──
if ($CheckPendingReboot) {
    $hasWork = $true
    Write-Host "`n=== Pending Reboot State ===" -ForegroundColor Cyan

    $pendingItems = @()

    # Check PendingFileRenameOperations
    try {
        $pfro = (Get-ItemProperty 'HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager' -Name PendingFileRenameOperations -ErrorAction Stop).PendingFileRenameOperations
        if ($pfro -and $pfro.Count -gt 0) {
            $pendingFiles = @()
            for ($j = 0; $j -lt $pfro.Count; $j += 2) {
                $src = $pfro[$j] -replace '^\\\?\?\\', ''
                if ($src) { $pendingFiles += $src }
            }
            if ($pendingFiles.Count -gt 0) {
                $pendingItems += [PSCustomObject]@{ Source='PendingFileRenameOperations'; Count=$pendingFiles.Count }
                Write-Host "  PendingFileRenameOperations: $($pendingFiles.Count) item(s)" -ForegroundColor Yellow
                foreach ($pf in $pendingFiles) {
                    Write-Host "    - $pf" -ForegroundColor DarkGray
                }
            }
        }
    } catch {
        Write-Host "  PendingFileRenameOperations: (not set)" -ForegroundColor Green
    }

    # Check delete-pending services (registry exists but CIM reports nothing)
    $svcRegPath = 'HKLM:\SYSTEM\CurrentControlSet\Services'
    $deletePending = @()
    Get-ChildItem $svcRegPath -ErrorAction SilentlyContinue | ForEach-Object {
        $svcName = $_.PSChildName
        try {
            $deleteFlag = (Get-ItemProperty $_.PSPath -Name DeleteFlag -ErrorAction Stop).DeleteFlag
            if ($deleteFlag -eq 1) { $deletePending += $svcName }
        } catch {}
    }
    if ($deletePending.Count -gt 0) {
        $pendingItems += [PSCustomObject]@{ Source='DeletePendingServices'; Count=$deletePending.Count }
        Write-Host "  Delete-pending services: $($deletePending.Count)" -ForegroundColor Yellow
        foreach ($dp in $deletePending) {
            Write-Host "    - $dp" -ForegroundColor DarkGray
        }
    }

    # Check Windows Update pending reboot
    $wuReboot = Test-Path 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\WindowsUpdate\Auto Update\RebootRequired'
    if ($wuReboot) {
        $pendingItems += [PSCustomObject]@{ Source='WindowsUpdate'; Count=1 }
        Write-Host "  Windows Update reboot required" -ForegroundColor Yellow
    }

    if ($pendingItems.Count -eq 0) {
        Write-Host "  No pending reboot state detected." -ForegroundColor Green
    } else {
        Write-Host "`n  ⚠️ Reboot is recommended to finalize pending operations." -ForegroundColor Yellow
    }
}

# ── No parameters: show quick overview ──
if (-not $hasWork) {
    Write-Host "Quick system overview — current state:" -ForegroundColor Cyan

    $autoSvc = (Get-CimInstance Win32_Service -Filter "StartMode='Auto'" | Measure-Object).Count
    $runningSvc = (Get-CimInstance Win32_Service -Filter "State='Running'" | Measure-Object).Count
    Write-Host "  Services: $autoSvc Auto, $runningSvc Running"

    $runEntries = 0
    @('HKCU:\Software\Microsoft\Windows\CurrentVersion\Run',
      'HKLM:\Software\Microsoft\Windows\CurrentVersion\Run') | ForEach-Object {
        $props = Get-ItemProperty $_ -ErrorAction SilentlyContinue
        if ($props) {
            $runEntries += ($props.PSObject.Properties |
                Where-Object { $_.Name -notmatch '^PS(Path|ParentPath|ChildName|Provider|Drive)$' }).Count
        }
    }
    Write-Host "  Startup items: $runEntries (HKCU+HKLM Run)"

    $enabledTasks = (Get-ScheduledTask -ErrorAction SilentlyContinue |
        Where-Object { $_.State -ne 'Disabled' -and $_.TaskPath -notmatch '^\\Microsoft\\' } |
        Measure-Object).Count
    Write-Host "  Non-Microsoft scheduled tasks (active): $enabledTasks"

    Write-Host "`nUse parameters to verify specific changes. Run Get-Help .\verify.ps1 for usage." -ForegroundColor DarkGray
    return
}

# ── Summary ──
Write-Host "`n$('=' * 40)" -ForegroundColor Cyan
$color = if ($failCount -eq 0) { 'Green' } else { 'Red' }
Write-Host "Verification complete: PASS $passCount | FAIL $failCount" -ForegroundColor $color
