#Requires -Version 5.1
<#
.SYNOPSIS
    win-sweep change verification — confirm optimization changes have taken effect.
.DESCRIPTION
    Re-scans services, startup items, and scheduled tasks to verify expected changes.
    Can compare against a backup CSV file to detect differences.
.PARAMETER BackupCsv
    Path to the backup CSV file generated by optimize-services.ps1 (optional).
    When provided, compares before/after differences.
.PARAMETER CheckServices
    Service list to verify (JSON format), same format as optimize-services.ps1.
    Example: '[{"Name":"DiagTrack","Target":"Disabled"}]'
.PARAMETER CheckTasks
    Array of scheduled task names to verify, expected to all be Disabled.
.PARAMETER CheckStartups
    Array of startup item names to verify have been removed from Run.
#>

[CmdletBinding()]
param(
    [string]$BackupCsv,
    [string]$CheckServices,
    [string[]]$CheckTasks,
    [string[]]$CheckStartups
)

$hasWork = $false
$passCount = 0
$failCount = 0

# ── Service verification ──
if ($CheckServices) {
    $hasWork = $true
    $svcList = $CheckServices | ConvertFrom-Json
    Write-Host "`n=== Service Status Verification ===" -ForegroundColor Cyan

    foreach ($item in $svcList) {
        $current = Get-CimInstance Win32_Service -Filter "Name='$($item.Name)'" -ErrorAction SilentlyContinue
        if (-not $current) {
            Write-Host "  [?] $($item.Name) — service not found" -ForegroundColor DarkYellow
            continue
        }

        $expected = switch ($item.Target) {
            'Manual'   { 'Manual' }
            'Disabled' { 'Disabled' }
            'Auto'     { 'Auto' }
        }

        if ($current.StartMode -eq $expected) {
            Write-Host "  [PASS] $($item.Name) = $($current.StartMode)" -ForegroundColor Green
            $passCount++
        } else {
            Write-Host "  [FAIL] $($item.Name) — expected $expected, actual $($current.StartMode)" -ForegroundColor Red
            $failCount++
        }
    }
}

# ── Scheduled task verification ──
if ($CheckTasks -and $CheckTasks.Count -gt 0) {
    $hasWork = $true
    Write-Host "`n=== Scheduled Task Status Verification ===" -ForegroundColor Cyan

    foreach ($taskName in $CheckTasks) {
        $task = Get-ScheduledTask -TaskName $taskName -ErrorAction SilentlyContinue
        if (-not $task) {
            Write-Host "  [?] $taskName — task not found" -ForegroundColor DarkYellow
            continue
        }

        if ($task.State -eq 'Disabled') {
            Write-Host "  [PASS] $taskName = Disabled" -ForegroundColor Green
            $passCount++
        } else {
            Write-Host "  [FAIL] $taskName — expected Disabled, actual $($task.State)" -ForegroundColor Red
            $failCount++
        }
    }
}

# ── Startup item verification ──
if ($CheckStartups -and $CheckStartups.Count -gt 0) {
    $hasWork = $true
    Write-Host "`n=== Startup Item Verification ===" -ForegroundColor Cyan

    $runPath = 'HKCU:\Software\Microsoft\Windows\CurrentVersion\Run'
    $disPath = 'HKCU:\Software\Microsoft\Windows\CurrentVersion\RunDisabled'

    foreach ($name in $CheckStartups) {
        $inRun = $false
        $inDisabled = $false
        try { $null = (Get-ItemProperty $runPath -Name $name -ErrorAction Stop); $inRun = $true } catch {}
        try { $null = (Get-ItemProperty $disPath -Name $name -ErrorAction Stop); $inDisabled = $true } catch {}

        if (-not $inRun -and $inDisabled) {
            Write-Host "  [PASS] '$name' — moved from Run to RunDisabled" -ForegroundColor Green
            $passCount++
        } elseif ($inRun) {
            Write-Host "  [FAIL] '$name' — still in Run (not disabled)" -ForegroundColor Red
            $failCount++
        } else {
            Write-Host "  [?] '$name' — not found in either Run or RunDisabled" -ForegroundColor DarkYellow
        }
    }
}

# ── Backup comparison ──
if ($BackupCsv) {
    $hasWork = $true
    Write-Host "`n=== Service Configuration Comparison (vs backup) ===" -ForegroundColor Cyan

    if (-not (Test-Path $BackupCsv)) {
        Write-Error "Backup file not found: $BackupCsv"
    } else {
        $before = Import-Csv $BackupCsv
        $changed = @()

        foreach ($old in $before) {
            $current = Get-CimInstance Win32_Service -Filter "Name='$($old.Name)'" -ErrorAction SilentlyContinue
            if ($current -and $current.StartMode -ne $old.StartMode) {
                $changed += [PSCustomObject]@{
                    Name    = $old.Name
                    Before  = $old.StartMode
                    After   = $current.StartMode
                    State   = $current.State
                }
            }
        }

        if ($changed.Count -gt 0) {
            Write-Host "  $($changed.Count) services have changed startup mode:" -ForegroundColor Yellow
            $changed | Format-Table -AutoSize
        } else {
            Write-Host "  No changes (all service startup modes match backup)." -ForegroundColor DarkGray
        }
    }
}

# ── No parameters: show quick overview ──
if (-not $hasWork) {
    Write-Host "Quick system overview — current state:" -ForegroundColor Cyan

    $autoSvc = (Get-CimInstance Win32_Service -Filter "StartMode='Auto'" | Measure-Object).Count
    $runningSvc = (Get-CimInstance Win32_Service -Filter "State='Running'" | Measure-Object).Count
    Write-Host "  Services: $autoSvc Auto, $runningSvc Running"

    $runEntries = 0
    @('HKCU:\Software\Microsoft\Windows\CurrentVersion\Run',
      'HKLM:\Software\Microsoft\Windows\CurrentVersion\Run') | ForEach-Object {
        $props = Get-ItemProperty $_ -ErrorAction SilentlyContinue
        if ($props) {
            $runEntries += ($props.PSObject.Properties |
                Where-Object { $_.Name -notmatch '^PS(Path|ParentPath|ChildName|Provider|Drive)$' }).Count
        }
    }
    Write-Host "  Startup items: $runEntries (HKCU+HKLM Run)"

    $enabledTasks = (Get-ScheduledTask -ErrorAction SilentlyContinue |
        Where-Object { $_.State -ne 'Disabled' -and $_.TaskPath -notmatch '^\\Microsoft\\' } |
        Measure-Object).Count
    Write-Host "  Non-Microsoft scheduled tasks (active): $enabledTasks"

    Write-Host "`nUse parameters to verify specific changes. Run Get-Help .\verify.ps1 for usage." -ForegroundColor DarkGray
    return
}

# ── Summary ──
Write-Host "`n$('=' * 40)" -ForegroundColor Cyan
$color = if ($failCount -eq 0) { 'Green' } else { 'Red' }
Write-Host "Verification complete: PASS $passCount | FAIL $failCount" -ForegroundColor $color
